name: activities
publish_to: 'none' 
version: 3.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

  ###CORE PACKAGES##################
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.0
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.20.3
  shared_preferences: ^2.2.2
  built_collection: ^5.1.1
  easy_date_timeline: ^1.0.3
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  stack_trace: ^1.11.0
  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  json_annotation: ^4.8.1
  timezone: ^0.9.2
  intl: ^0.19.0
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  readmore: ^3.0.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_adaptive_scaffold: ^0.1.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.0
  flutter_downloader: ^1.11.7
  sn_progress_dialog: ^1.1.4
  rxdart: ^0.27.7
  flutter_html: ^3.0.0-beta.2
  drop_down_list: ^0.0.6
  rotated_corner_decoration: ^2.1.0+1
  lottie: ^3.1.0
  # moyasar: ^2.0.13
  motion_tab_bar: ^2.0.4
  restart_app: 1.2.1
  
  
 


  ###RESPONSIVE#####################
  responsive_builder: ^0.7.0
  get_it: ^7.6.7


  ###UI ENHANCEMENT#####################
  showcaseview: ^2.0.3
  skeletonizer: ^1.0.1
  badges: ^3.1.2
  pinput: ^3.0.1
  flutter_credit_card: ^4.0.1
  flutter_blurhash: ^0.8.2
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop 
 # intl_phone_number_input: ^0.7.3+1
  flutter_side_menu: ^0.4.0
  country_code_picker: ^3.0.0
  multi_select_flutter: ^4.1.3
  pin_code_fields: ^8.0.1


############HELPERS #################################
  file_picker: ^6.0.0
  url_launcher: ^6.2.2
  faker: ^2.1.0
  crypto: ^3.0.3
  uuid: ^4.1.0
  json_path: ^0.7.0
  package_info_plus: ^5.0.1
  geolocator: ^10.1.0
  path_provider: ^2.1.1
  url_strategy: ^0.2.0
  modal_bottom_sheet: ^2.1.2
  persistent_bottom_nav_bar: ^5.0.2
  floating_bottom_bar: ^0.0.2
  flutter_launcher_icons: ^0.13.1
  credit_card_validator: ^2.1.0
  credit_card_type_detector: ^3.0.0
  month_year_picker: ^0.4.0+1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  extended_phone_number_input: ^1.0.2
  awesome_dialog: ^3.2.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  flutter_pdfview: ^1.3.2
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  moyasar: ^2.0.7
  pay: ^1.1.2
  
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  custom_lint: ^0.5.6 # other lints depend on this
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  random_string: ^2.3.1
  build_runner: ^2.1.10
  freezed: ^2.4.5
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.8
  hive_generator: ^2.0.1
  change_app_package_name: ^1.1.0
  analyzer: 6.2.0

flutter:
  generate: true
  uses-material-design: true
 
  assets:
    - assets/images/
    - assets/lottie/
    

  fonts:
    - family: arabicFont
      fonts:
        - asset: assets/fonts/arabic-font.OTF
          weight: 600

    


flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated